# Generated by Django 4.1.1 on 2022-09-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_participation_unique event_match_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='matches.participation'),
        ),
    ]
