# Generated by Django 4.1.1 on 2022-09-29 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bo_games',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_in_match', to='matches.participation'),
        ),
        migrations.AddField(
            model_name='match',
            name='losing_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 5, 23, 27, 884572)),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_in_match', to='matches.participation'),
        ),
        migrations.AddField(
            model_name='match',
            name='winning_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='have_matches', to='matches.participation'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('winning_score', models.PositiveSmallIntegerField(default=0)),
                ('losing_score', models.PositiveSmallIntegerField(default=0)),
                ('duration', models.DurationField()),
                ('blue_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_blue', to='matches.participation')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_game', to='matches.participation')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('red_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_red', to='matches.participation')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_game', to='matches.participation')),
            ],
        ),
    ]
