# Generated by Django 4.1.1 on 2022-09-29 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_game_public_id_match_public_id_series_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 6, 44, 8, 559392)),
        ),
    ]
