# Generated by Django 4.1.1 on 2022-09-29 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 6, 47, 30, 476600)),
        ),
        migrations.AlterField(
            model_name='series',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
