# Generated by Django 4.1.1 on 2022-09-29 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_game_public_id_alter_match_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 6, 53, 52, 141305)),
        ),
    ]
