# Generated by Django 4.1.1 on 2022-09-27 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, default=datetime.date.today)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Analyst'), ('R', 'Retired'), ('I', 'Inactive'), ('L', 'Loan'), ('C', 'Coach'), ('P', 'Player')], default='P', max_length=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_of', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(default='ezml_logo_opac.svg', null=True, upload_to='')),
                ('slug', models.SlugField(null=True)),
                ('members', models.ManyToManyField(through='teams.Membership', to='players.player')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_members', to='teams.team'),
        ),
    ]
