# Generated by Django 4.1.1 on 2022-09-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
