# Generated by Django 4.1.1 on 2022-09-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='country',
        ),
    ]
