# Generated by Django 4.1.1 on 2022-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
