# Generated by Django 4.1.1 on 2022-09-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='status',
        ),
    ]
