# Generated by Django 4.1.1 on 2022-10-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_public_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('player', 'date_joined'), name='unique_transfer'),
        ),
    ]
