# Generated by Django 4.1.1 on 2022-09-20 16:20

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

import json
import os
from pathlib import Path
import datetime

current_path = Path().absolute()
file_list = []
fixture_folder = os.path.join(current_path, 'teams', 'fixtures')
for filename in os.listdir(fixture_folder):
    obj_file = filename.split("_")
    if obj_file[0] == "member" and obj_file[1] == "info":
        f = os.path.join(fixture_folder, filename)
        # checking if it is a file
        if os.path.isfile(f):
            file_list.append(f)

def add_member(apps, schema_editor):
    Member = apps.get_model('teams', 'Membership')
    Player = apps.get_model('players', 'Player')
    Team = apps.get_model('teams', 'Team')
    for file_exp in file_list:
        file_exp = json.load(open(file_exp, 'r'))
        for data_ele in file_exp:
            insp_pk = data_ele['pk']
            # Initial commit, Member should be empty
            player_obj = Player.objects.get(pk=data_ele['fields']["player"])
            team_obj = Team.objects.get(pk=data_ele['fields']['team'])
            format = "%Y-%m-%d"
            d_join = datetime.datetime.strptime(data_ele['fields']['date_joined'], format).date()
            if data_ele['fields']['date_left']:
                d_left = datetime.datetime.strptime(data_ele['fields']['date_left'], format).date()
            else:
                d_left = None
            Member.objects.create(pk=insp_pk, player=player_obj, 
            team=team_obj, date_joined=d_join, date_left=d_left)

class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20220920_1751'),
        ('players', '0012_auto_20220920_1557'),
    ]

    operations = [
        migrations.RunPython(add_member),
    ]
