# Generated by Django 4.1.1 on 2022-09-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20220920_1557'),
        ('teams', '0007_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_of', to='players.player'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('A', 'Analyst'), ('R', 'Retired'), ('I', 'Inactive'), ('L', 'Loan'), ('C', 'Coach'), ('P', 'Player')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_members', to='teams.team'),
        ),
    ]
