# Generated by Django 4.1.1 on 2022-09-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['position', '-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='thread',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
