# Generated by Django 4.1.1 on 2022-09-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_comment_options_rename_thread_comment_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='thread',
        ),
    ]
