# Generated by Django 4.1.1 on 2022-09-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
