# Generated by Django 4.1.1 on 2022-09-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_alter_thread_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='description',
        ),
    ]
