# Generated by Django 4.1.1 on 2022-09-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_remove_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subforum',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
