# Generated by Django 4.1.1 on 2022-09-27 21:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('role', models.CharField(choices=[('P', 'Player'), ('A', 'Analyst'), ('C', 'Coach'), ('S', 'Caster')], default='P', max_length=1)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(default='avatar.svg', upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('alternate_ids', models.CharField(blank=True, max_length=300, null=True)),
                ('earning', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('R', 'Retired'), ('I', 'Inactive'), ('L', 'Loan')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('vk', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='players.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.position'),
        ),
    ]
