# Generated by Django 4.1.1 on 2022-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_fullname_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('P', 'Player'), ('A', 'Analyst'), ('C', 'Coach'), ('S', 'Caster')], default='P', max_length=1),
        ),
    ]
