# Generated by Django 4.1.1 on 2022-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20220929_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='public_id',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
