# Generated by Django 4.1.1 on 2022-09-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='public_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
