# Generated by Django 4.1.1 on 2022-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_current_team_player_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_team',
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='players.position'),
        ),
    ]
