# Generated by Django 4.1.1 on 2022-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
