# Generated by Django 4.1.1 on 2022-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_socialmedia_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='public_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
