# Generated by Django 4.1.1 on 2022-09-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_position_remove_player_current_team_player_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='players', to='players.position'),
        ),
    ]
