# Generated by Django 4.1.1 on 2022-10-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_socialmedia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
