# Generated by Django 4.1.1 on 2022-10-01 13:25

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_socialmedia_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='avatar.svg', upload_to=players.models.upload_to),
        ),
    ]
