# Generated by Django 4.1.1 on 2022-09-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_player_earning_player_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='positions',
            new_name='position',
        ),
    ]
