# Generated by Django 4.1.1 on 2022-09-26 14:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20220920_1557'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('search_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
