# Generated by Django 4.1.1 on 2022-09-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_player_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
